font_family      JetBrainsMono Nerd Font
font_size        12.0
bold_font        auto
italic_font      auto
bold_italic_font auto

# Catppuccin Mocha
foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #F5C2E7

color0  #45475A
color1  #F38BA8
color2  #A6E3A1
color3  #F9E2AF
color4  #89B4FA
color5  #F5C2E7
color6  #94E2D5
color7  #BAC2DE
color8  #585B70
color9  #F38BA8
color10 #A6E3A1
color11 #F9E2AF
color12 #89B4FA
color13 #F5C2E7
color14 #94E2D5
color15 #A6ADC8

cursor                  #F5C2E7
cursor_text_color       #1E1E2E
url_color               #F5C2E7

background_opacity 0.85
window_padding_width 10

startup_session none
shell_integration enabled

# Run fastfetch on open
startup_session none
allow_remote_control yes
confirm_os_window_close 0
